# KONSPECTO/docker-compose.yml
services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        VITE_API_URL: /api/v1
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    env_file: "backend/app/config/.env"
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/app/config:/app/config
      - huggingface_cache:/app/.cache/huggingface
      # - ./backend/generated_docs:/app/generated_docs  # Remove this line
    environment:
      - PYTHON_ENV=production
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis-stack:6379
      - HF_HOME=/app/.cache/huggingface
      - LLM_STUDIO_BASE_URL=${LLM_STUDIO_BASE_URL}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis-stack:
        condition: service_healthy
    restart: unless-stopped

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_stack_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  vllm-openai:
    env_file: "backend/app/config/.env"
    image: vllm/vllm-openai:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8002:8000"
    volumes:
      - huggingface_cache:/app/.cache/huggingface
    environment:
      - HF_HOME=/app/.cache/huggingface
      - MODEL_NAME=${MODEL_NAME}
    ipc: "host"
    command: "--model ${MODEL_NAME}"
    profiles: [vllm]

volumes:
  redis_stack_data:
  huggingface_cache:
